package com.cioccarellia.checkpigeon.logic.console

fun String.black() = Tint.f(this, TerminalColor.BLACK)
fun String.red() = Tint.f(this, TerminalColor.RED)
fun String.green() = Tint.f(this, TerminalColor.GREEN)
fun String.yellow() = Tint.f(this, TerminalColor.YELLOW)
fun String.blue() = Tint.f(this, TerminalColor.BLUE)
fun String.magenta() = Tint.f(this, TerminalColor.MAGENTA)
fun String.cyan() = Tint.f(this, TerminalColor.CYAN)
fun String.lightGray() = Tint.f(this, TerminalColor.LIGHT_GRAY)
fun String.lightRed() = Tint.f(this, TerminalColor.LIGHT_RED)
fun String.lightGreen() = Tint.f(this, TerminalColor.LIGHT_GREEN)
fun String.lightYellow() = Tint.f(this, TerminalColor.LIGHT_YELLOW)
fun String.lightBlue() = Tint.f(this, TerminalColor.LIGHT_BLUE)
fun String.lightMagenta() = Tint.f(this, TerminalColor.LIGHT_MAGENTA)
fun String.lightCyan() = Tint.f(this, TerminalColor.LIGHT_CYAN)
fun String.lightWhite() = Tint.f(this, TerminalColor.WHITE)

fun String.blackBackground() = Tint.b(this, TerminalColor.BLACK)
fun String.redBackground() = Tint.b(this, TerminalColor.RED)
fun String.greenBackground() = Tint.b(this, TerminalColor.GREEN)
fun String.yellowBackground() = Tint.b(this, TerminalColor.YELLOW)
fun String.blueBackground() = Tint.b(this, TerminalColor.BLUE)
fun String.magentaBackground() = Tint.b(this, TerminalColor.MAGENTA)
fun String.cyanBackground() = Tint.b(this, TerminalColor.CYAN)
fun String.lightGrayBackground() = Tint.b(this, TerminalColor.LIGHT_GRAY)
fun String.lightRedBackground() = Tint.b(this, TerminalColor.LIGHT_RED)
fun String.lightGreenBackground() = Tint.b(this, TerminalColor.LIGHT_GREEN)
fun String.lightYellowBackground() = Tint.b(this, TerminalColor.LIGHT_YELLOW)
fun String.lightBlueBackground() = Tint.b(this, TerminalColor.LIGHT_BLUE)
fun String.lightMagentaBackground() = Tint.b(this, TerminalColor.LIGHT_MAGENTA)
fun String.lightCyanBackground() = Tint.b(this, TerminalColor.LIGHT_CYAN)
fun String.lightWhiteBackground() = Tint.b(this, TerminalColor.WHITE)