package com.cioccarellia.checkpigeon.logic.console

fun String.black() = Tinter.f(this, Color.BLACK)
fun String.red() = Tinter.f(this, Color.RED)
fun String.green() = Tinter.f(this, Color.GREEN)
fun String.yellow() = Tinter.f(this, Color.YELLOW)
fun String.blue() = Tinter.f(this, Color.BLUE)
fun String.magenta() = Tinter.f(this, Color.MAGENTA)
fun String.cyan() = Tinter.f(this, Color.CYAN)
fun String.lightGray() = Tinter.f(this, Color.LIGHT_GRAY)
fun String.lightRed() = Tinter.f(this, Color.LIGHT_RED)
fun String.lightGreen() = Tinter.f(this, Color.LIGHT_GREEN)
fun String.lightYellow() = Tinter.f(this, Color.LIGHT_YELLOW)
fun String.lightBlue() = Tinter.f(this, Color.LIGHT_BLUE)
fun String.lightMagenta() = Tinter.f(this, Color.LIGHT_MAGENTA)
fun String.lightCyan() = Tinter.f(this, Color.LIGHT_CYAN)
fun String.lightWhite() = Tinter.f(this, Color.WHITE)

fun String.blackBackground() = Tinter.b(this, Color.BLACK)
fun String.redBackground() = Tinter.b(this, Color.RED)
fun String.greenBackground() = Tinter.b(this, Color.GREEN)
fun String.yellowBackground() = Tinter.b(this, Color.YELLOW)
fun String.blueBackground() = Tinter.b(this, Color.BLUE)
fun String.magentaBackground() = Tinter.b(this, Color.MAGENTA)
fun String.cyanBackground() = Tinter.b(this, Color.CYAN)
fun String.lightGrayBackground() = Tinter.b(this, Color.LIGHT_GRAY)
fun String.lightRedBackground() = Tinter.b(this, Color.LIGHT_RED)
fun String.lightGreenBackground() = Tinter.b(this, Color.LIGHT_GREEN)
fun String.lightYellowBackground() = Tinter.b(this, Color.LIGHT_YELLOW)
fun String.lightBlueBackground() = Tinter.b(this, Color.LIGHT_BLUE)
fun String.lightMagentaBackground() = Tinter.b(this, Color.LIGHT_MAGENTA)
fun String.lightCyanBackground() = Tinter.b(this, Color.LIGHT_CYAN)
fun String.lightWhiteBackground() = Tinter.b(this, Color.WHITE)