package com.cioccarellia.checkpigeon.logic.console

fun String.black() = Tinter.f(this, TerminalColor.BLACK)
fun String.red() = Tinter.f(this, TerminalColor.RED)
fun String.green() = Tinter.f(this, TerminalColor.GREEN)
fun String.yellow() = Tinter.f(this, TerminalColor.YELLOW)
fun String.blue() = Tinter.f(this, TerminalColor.BLUE)
fun String.magenta() = Tinter.f(this, TerminalColor.MAGENTA)
fun String.cyan() = Tinter.f(this, TerminalColor.CYAN)
fun String.lightGray() = Tinter.f(this, TerminalColor.LIGHT_GRAY)
fun String.lightRed() = Tinter.f(this, TerminalColor.LIGHT_RED)
fun String.lightGreen() = Tinter.f(this, TerminalColor.LIGHT_GREEN)
fun String.lightYellow() = Tinter.f(this, TerminalColor.LIGHT_YELLOW)
fun String.lightBlue() = Tinter.f(this, TerminalColor.LIGHT_BLUE)
fun String.lightMagenta() = Tinter.f(this, TerminalColor.LIGHT_MAGENTA)
fun String.lightCyan() = Tinter.f(this, TerminalColor.LIGHT_CYAN)
fun String.lightWhite() = Tinter.f(this, TerminalColor.WHITE)

fun String.blackBackground() = Tinter.b(this, TerminalColor.BLACK)
fun String.redBackground() = Tinter.b(this, TerminalColor.RED)
fun String.greenBackground() = Tinter.b(this, TerminalColor.GREEN)
fun String.yellowBackground() = Tinter.b(this, TerminalColor.YELLOW)
fun String.blueBackground() = Tinter.b(this, TerminalColor.BLUE)
fun String.magentaBackground() = Tinter.b(this, TerminalColor.MAGENTA)
fun String.cyanBackground() = Tinter.b(this, TerminalColor.CYAN)
fun String.lightGrayBackground() = Tinter.b(this, TerminalColor.LIGHT_GRAY)
fun String.lightRedBackground() = Tinter.b(this, TerminalColor.LIGHT_RED)
fun String.lightGreenBackground() = Tinter.b(this, TerminalColor.LIGHT_GREEN)
fun String.lightYellowBackground() = Tinter.b(this, TerminalColor.LIGHT_YELLOW)
fun String.lightBlueBackground() = Tinter.b(this, TerminalColor.LIGHT_BLUE)
fun String.lightMagentaBackground() = Tinter.b(this, TerminalColor.LIGHT_MAGENTA)
fun String.lightCyanBackground() = Tinter.b(this, TerminalColor.LIGHT_CYAN)
fun String.lightWhiteBackground() = Tinter.b(this, TerminalColor.WHITE)